---
title: Sensorische gadget
hero_image: images/banner.png
description: Maak een sensorische gadget met je Raspberry Pi Pico
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Jouw idee
  - 
    title: Bouwen en testen
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Deel
  - 
    title: Wat kun je verder nog doen?
