---
title: Gadget sensoriel
hero_image: images/banner.png
description: Créer un gadget sensoriel à l'aide de ton Raspberry Pi Pico
meta_title: Raspberry Pi Pico projects | Sensory gadget
meta_description: A Raspberry Pi Pico project to create a fidget toy or sensory gadget using buttons, potentiometers, LEDs, and a buzzer.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Ton idée
  - 
    title: Construire et tester
    completion:
      - engaged
      - internal
  - 
    title: Liste de contrôle
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
